spring.application.name=AutoUpdateService
# --- Server ---
server.port=8080
server.forward-headers-strategy=framework
server.servlet.session.timeout=12h

# --- DataSource (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/auto_update_1c
spring.datasource.username=app
spring.datasource.password=app

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true

# --- Flyway ---
spring.flyway.enabled=true

# --- Thymeleaf ---
spring.thymeleaf.cache=false

# --- GitLab Webhook ---
gitlab.webhook.secret=${GITLAB_WEBHOOK_SECRET:change-me}

# --- GitLab API ---
gitlab.api.base-url=${GITLAB_API_BASE_URL:http://10.0.1.85}
gitlab.api.token=${GITLAB_API_TOKEN:glpat-BD9WF_PUAJPm8Agx7gwggm86MQp1OjMH.01.0w1gnhedt}

# --- Runner settings ---
runner.binary=${RUNNER_BINARY:runner}
runner.ras-address=${RUNNER_RAS_ADDRESS:erp-2:1745}
runner.rac-path=${RUNNER_RAC_PATH:C:/Program Files/1cv8/8.3.27.1859/bin/rac.exe}
runner.base-name=${RUNNER_BASE_NAME:ERPBigAuto}
runner.ib-connection=${RUNNER_IB_CONNECTION:Srvr=\"erp-2:1741\";Ref=\"ERPBigAuto\"}
runner.db-user=${RUNNER_DB_USER:\u0411\u043E\u0433\u043E\u043C\u043E\u043B\u043E\u0432\u0421\u0418}
runner.db-password=${RUNNER_DB_PASSWORD:enamiS65}
runner.repo-user=${RUNNER_REPO_USER:\u0410\u0432\u0442\u043E}
runner.repo-password=${RUNNER_REPO_PASSWORD:storage_pass}
runner.log-dir=${RUNNER_LOG_DIR:./runner-logs}
runner.lockMessage=${RUNNER_LOCKMESSAGE:"Update base"}
runner.uccode=${RUNNER_UCCODE:update}
runner.mainRepoPath=${RUNNER_MAINREPOPATH:tcp://erp-bd-01:1642/ERP258}
runner.extRepoPath=${RUNNER_EXTREPOPATH:tcp://erp-bd-01:1642/ERP258-Ext}
runner.ib-connectionrepo=${RUNNER_CONNECTIONREPO:/Serp-2:1741/ERPBigAuto}
runner.ext=${RUNNER_EXTREPOPATH:_\u041E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\u043E\u0435\u0420\u0430\u0441\u0448\u0438\u0440\u0435\u043D\u0438\u0435}
runner.keep-days=${RUNNER_KEEP_DAYS:1}

# --- Scheduler ---
app.scheduler.poll-cron=${APP_SCHEDULER_POLL_CRON:0 * * * * *}
# --- Windows console (??? ????????? ? .cmd) ---
runner.windows-code-page=${RUNNER_WINDOWS_CODE_PAGE:65001}


# --- Steps plan (JSON) ---
runner.steps-file=${RUNNER_STEPS_FILE:./runner-steps.default.json}
